export const addFile = "Add File"
export const from = "From"
export const to = "To"
export const share = "Share"
export const toAddressPlaceHolder = "To Address"
export const confirmed = "You have successfully shared a file"